generator: admingenerator.generator.doctrine
params:
  model: Lyd\AdminBundle\Entity\Comision
  namespace_prefix: Lyd
  bundle_name: AdminBundle
  fields: 
    digito:
      label: Digito Verificador

builders:
  list:
    params:
      title: Comisiones
      display: [ digito, nombre]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Nueva Comisión
      display: [ digito, nombre]
      actions:
        list: ~
  edit:
    params:
      title: Editar "%object%"|{ %object%: Comision.nombre }|
      display: [ digito, nombre]
      actions:
        list: ~
  delete: ~
