generator: admingenerator.generator.doctrine
params:
  i18n_catalog: RegistroLegislativo
  model: Lyd\AdminBundle\Entity\Ministerio
  namespace_prefix: Lyd
  bundle_name: AdminBundle
  fields: 
    digito:
      label: Digito Verificador

builders:
  list:
    params:
      title: Ministerios
      display: [ digito, nombre]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ nombre ]
  new:
    params:
      title: Nuevo Ministerio
      display: [ digito, nombre]
      actions:
        list: ~
  edit:
    params:
      title: Editar "%object%"|{ %object%: Ministerio.nombre }|
      display: [ digito, nombre]
      actions:
        list: ~
  delete: ~
