generator: admingenerator.generator.doctrine
params:
  i18n_catalog: RegistroLegislativo
  model: Lyd\AdminBundle\Entity\RegistroLegislativo
  namespace_prefix: Lyd
  bundle_name: AdminBundle
  fields: 
    fecha_cuenta:
      formType: birthday
      addFormOptions:
        format: "d-M-y"
        years:
          .range:
            from: <?php echo date("Y"); ?>
            
            to: 1970
            step: 1  
    iniciativa:
      label: Iniciativa
      formType: choice
      addFormOptions:
        choices:
          mensaje: Mensaje
          mocion: Moción    
    origen:
      label: Origen
      formType: choice
      addFormOptions:
        choices:
          camara: Camara
          ejecutivo: Ejecutivo
    resena:
      label: Reseña
    fecha_resena:
      label: Fecha Reseña
      formType: birthday
      addFormOptions:
        format: "d-M-y"
        years:
          .range:
            from: <?php echo date("Y"); ?>
            
            to: 1970
            step: 1
      

builders:
  list:
    batch_actions:
    delete: ~
    params:
      title: Registros Legislativo
      display: [numero_boletin, comision, suma_proyecto, estado]
      sort: [ id, DESC ]
      actions:
        new: ~
      object_actions:
        delete:
          confirm: ¿Está seguro de eliminar registro?
  filters:
    params:
      display: [ fecha_cuenta, estado, iniciativa, origen]
  new:
    params:
      title: Nuevo Registro Legislativo
      fields: 
        comision:
          label: ~
        estado:
          formType: choice
          addFormOptions:
            choices:
              true: Activo
              false: Inactivo
        suma_proyecto:
          addFormOptions:
            attr:
              class: textarea_sm
        resumen:
          addFormOptions:
            attr:
              class: textarea_sm
        descriptor:
          addFormOptions:
            attr:
              class: textarea_sm
        resena:
          addFormOptions:
            attr:
              class: textarea_sm      
              
      display:
        NONE: [[numero_boletin, comision]]
        "Legis": [fecha_cuenta, estado, iniciativa, origen, suma_proyecto, resumen, descriptor, resena, fecha_resena]
      actions:
        list: ~
  edit:
    params:
      title: Editar
      display: [suma_proyecto]
      actions:
        list: ~
  delete: ~
