Lyd\AdminBundle\Entity\RegistroLegislativo:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        numero_boletin:
            type: integer
            length: 255
        fecha_cuenta:
            type: date
            nullable: true
        estado:
            type: boolean
            nullable: true
        iniciativa:
            type: string 
            nullable: true
        origen:
            type: string
            nullable: true
        suma_proyecto:
            type: text
            nullable: true
        resumen:
            type: text
            nullable: true
        descriptor:
            type: text
            nullable: true
        resena:
            type: text
            nullable: true
        fecha_resena:
            type: date
            nullable: true
        reglamentos:
            type: text
            nullable: true
        numero_decreto:
            type: integer
            nullable: true
        fecha_diario_oficial:
            type: date
            nullable: true
        observaciones:
            type: text
            nullable: true
        fecha_rechazo:
            type: date
            nullable: true
        fecha_retiro:
            type: date
            nullable: true
        fecha_archivo:
            type: date
            nullable: true
        fecha_publicacion:
            type: date
            nullable: true
        numero_ley:
            type: integer
            nullable: true
        numero_decreto:
            type: integer
            nullable: true
        fecha_fallo_1:
            type: date
            nullable: true
        fecha_fallo_2:
            type: date
            nullable: true
    manyToOne:
      investigador:
        targetEntity: Lyd\AdminBundle\Entity\Investigador
        joinColumn:
          name: investigador_id
          referencedColumnName: id
      encargado:
        targetEntity: Lyd\AdminBundle\Entity\EncargadoLegislativo
        joinColumn:
          name: encargado_id
          referencedColumnName: id    
      ministerio:
        targetEntity: Lyd\AdminBundle\Entity\Ministerio
        joinColumn:
          name: ministerio_id
          referencedColumnName: id    
    lifecycleCallbacks: {  }
